[phases.setup]
nixPkgs = ["nodejs-22_x"]

[phases.install]
cmds = [
  "npm install --prefix backend --legacy-peer-deps",
  "npm install --prefix frontend --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "node backend/server.js"
